BOARD_ROWS = 25
BOARD_COLS = 50
CELL_SIZE = 20
FLAG_ROWS = 3

WINDOW_WIDTH = BOARD_COLS * CELL_SIZE
WINDOW_HEIGHT = BOARD_ROWS * CELL_SIZE

SOLDIER_ROWS = 4
SOLDIER_COLS = 2
SOLDIER_BODY_ROWS = 3
SOLDIER_FEET_ROWS = 1

PLAYER_WIDTH = SOLDIER_COLS * CELL_SIZE
PLAYER_HEIGHT = SOLDIER_ROWS * CELL_SIZE

FLAG_ROWS = 3
FLAG_COLS = 4

MINES_COUNT = 20
MINE_ROWS = 1
MINE_COLS = 3

EMPTY = "empty"
FLAG = "flag"
MINE = "mine"

WELCOME_MESSAGE = "Welcome to The Flag game.\n Have Fun!"

