BOARD_ROWS = 35
BOARD_COLS = 70
CELL_SIZE = 20
FLAG_ROWS = 3

WINDOW_WIDTH = BOARD_COLS * CELL_SIZE
WINDOW_HEIGHT = BOARD_ROWS * CELL_SIZE

SOLDIER_ROWS = 9
SOLDIER_COLS = 4
SOLDIER_BODY_ROWS = 3
SOLDIER_FEET_ROWS = 1

PLAYER_WIDTH = SOLDIER_COLS * CELL_SIZE
PLAYER_HEIGHT = SOLDIER_ROWS * CELL_SIZE

FLAG_ROWS = 6
FLAG_COLS = 6

FLAG_WIDTH = FLAG_COLS * CELL_SIZE
FLAG_HEIGHT = FLAG_ROWS * CELL_SIZE

MINES_COUNT = 20
MINE_ROWS = 1
MINE_COLS = 3

MINE_HEIGHT = MINE_ROWS*CELL_SIZE
MINE_WIDTH = MINE_COLS*CELL_SIZE

EMPTY = "empty"
FLAG = "flag"
MINE = "mine"

WELCOME_MESSAGE = "Welcome to The Flag game.\n Have Fun!"

RUNNING_STATE = 1
LOSE_STATE = 2
WIN_STATE = 3

GRASS_ROWS = 3
GRASS_COLS = 3


FONT_NAME = "Calibri"
LOSE_MESSAGE = "You Lost!"
LOSE_FONT_SIZE = int(0.15 * WINDOW_WIDTH)
LOSE_COLOR = (0,0,0)
LOSE_LOCATION = \
    (0.2 * WINDOW_WIDTH, WINDOW_HEIGHT / 2 - (LOSE_FONT_SIZE / 2))
WIN_MESSAGE = "You Won!"
WIN_FONT_SIZE = LOSE_FONT_SIZE
WIN_COLOR = (89, 89, 89)
WIN_LOCATION = \
    (0.2 * WINDOW_WIDTH, WINDOW_HEIGHT / 2 - (WIN_FONT_SIZE / 2))


GRASS_WIDTH = GRASS_COLS * CELL_SIZE
GRASS_HEIGHT = GRASS_ROWS * CELL_SIZE
